# Generated by Django 5.0.7 on 2025-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLog',
        ),
    ]
